// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'
// import { ReactNode } from 'react'
// import { ThemeProvider } from '@/components/theme-provider'

// const geistSans = Geist({
//    variable: '--font-geist-sans',
//    subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//    variable: '--font-geist-mono',
//    subsets: ['latin'],
// })

// export const metadata: Metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// }

// interface RootLayoutProps {
//    children: ReactNode
// }

// export default function RootLayout({ children }: RootLayoutProps) {
//    return (
//       <html lang="en">
//          <body
//             className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//          >
//             <ThemeProvider
//                attribute="class"
//                defaultTheme="system"
//                enableSystem
//                disableTransitionOnChange
//             >
//                {children}
//             </ThemeProvider>
//          </body>
//       </html>
//    )
// }

//Vercel code

import type React from 'react'
import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import { ThemeProvider } from '@/components/theme-provider'

import './globals.css'

export const metadata: Metadata = {
   title: 'ShopNow - Online Shopping',
   description: 'Modern e-commerce website built with Next.js',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body
            className={`${GeistSans.variable} ${GeistMono.variable} font-sans antialiased`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   )
}
